# Generated by Django 4.1.6 on 2023-03-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
